[作業目標]

[簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

[簡答題] 承上題，請判斷下列三種寫法為何不正確？

def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)

作業
1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

print('type(a): ', type(a))

print('a.dtype: ', a.dtype)

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print('type(a):',type(a))  # type(a) 查看a類型

type(a): <class 'numpy.ndarray'>


In [6]:
print('a.dtype:',a.dtype)  # a.dtype 查看a的資料型態

a.dtype: int32


2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。

In [7]:
# 記得先 Import 正確的套件
import numpy as np

In [41]:
def is_dtype(a,t):
    return a.dtype is np.dtype(t)

In [42]:
a = np.random.randint(10,size=6)
print(a)

[2 1 8 0 4 9]


In [44]:
print(is_dtype(a,'int'))
print(is_dtype(a, np.int))
print(is_dtype(a, np.dtype('int')))

True
True
True


3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)

In [ ]:
ANS: 
type(a):查看a類型；np.dtype():表示資料型態為()。
因類型和資料型態不同，所以第二、三種寫法不正確。