[作業目標]

[簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

print(np.zeros((2, 3)))

print(np.empty((2, 3)))

在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

作業
1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [24]:
import numpy as np
a = np.empty((5,5))
print(a)
%timeit a

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33644129e-307
  1.33511018e-306]
 [1.33511969e-306 6.23037996e-307 6.23053954e-307 9.34609790e-307
  8.45593934e-307]
 [9.34600963e-307 1.86921143e-306 6.23061763e-307 6.23060065e-307
  2.22522597e-306]
 [1.06810268e-306 6.23052935e-307 8.45603441e-307 9.79111267e-307
  8.45559303e-307]
 [1.06811422e-306 1.05694828e-307 2.22522596e-306 2.22507386e-306
  4.89124989e-322]]
26.3 ns ± 0.385 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [28]:
b = np.zeros((5,5))
print(b)
%timeit b

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
26.2 ns ± 0.253 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [39]:
%timeit np.empty((1000,500))
%timeit np.zeros((1000,500))

13.8 µs ± 86.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.2 µs ± 141 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


ANS:

(1)np.zeros((x,y)) 為0矩陣；np.empty((x,y)) 為非0矩陣，其中各元素值很接近零

(2)如需初始化則使用np.zeros((x,y))；若不須初始化使用np.empty((x,y))大量數據的狀況下處理時間較短

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [5]:
import numpy as np
a = np.random.random((5,4))*100
print(a)

[[80.9091   0.55686 55.62442 52.3959 ]
 [93.01816 96.8051  52.43574 37.13099]
 [87.96314 87.97212 60.08933 23.62343]
 [33.03572 73.04359 77.972   70.00941]
 [43.30398 51.08057 86.86774 96.58319]]


In [7]:
np.set_printoptions(precision=0)
print(a)

[[81.  1. 56. 52.]
 [93. 97. 52. 37.]
 [88. 88. 60. 24.]
 [33. 73. 78. 70.]
 [43. 51. 87. 97.]]


ANS:
    加入np.set_printoptions(precision=x),x為小數位數限制

3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [2]:
import numpy as np
m = 20
n = 40
a = np.random.randint(m,n,size=(5,4))
print(a)


[[21 36 23 27]
 [32 30 27 26]
 [33 20 24 34]
 [39 33 30 26]
 [38 34 26 21]]


作業目標

在一個陣列中放入多屬性陣列，進一步對陣列做運算

作業重點

在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性


題目:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]


將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
呈上題，將array中體重(weight)數據集取出算出全部平均體重
呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [2]:
import numpy as np
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [3]:
dt = np.dtype({'names':('Name','sex','weight','rank','myopia'),'formats':('U4','U4',float,int,bool)})
c = np.zeros(8,dtype=dt)
c

array([('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False)],
      dtype=[('Name', '<U4'), ('sex', '<U4'), ('weight', '<f8'), ('rank', '<i4'), ('myopia', '?')])

In [4]:
c['Name'] = name_list
c['sex'] = sex_list
c['weight'] = weight_list
c['rank'] = rank_list
c['myopia'] = myopia_list
print(c)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

In [6]:
np.mean(c['weight'])

69.8375

#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重

In [10]:
np.mean(c[c['sex']=='boy']['weight'])

77.18333333333332

#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重

In [13]:
c[c['sex']=='girl']['weight'].mean()

47.8